RoomReservation/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RoomReservation.Models
{
    // Soba ima sledeće atribute: Id, Broj sobe, Broj kreveta, Cena po noćenju
    public class Room
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Room Number")]
        public int RoomNumber { get; set; }

        [Required]
        [Display(Name = "Bed Number")]
        public int BedNumber { get; set; }

        [Required]
        public decimal Price { get; set; }

        public virtual Accommodation Accommodation { get; set; }
        public int? AccommodationId { get; set; }

        public virtual ICollection<Reservation> Reservations { get; set; }

    }
}

RoomReservation/Controllers/RoomsController.cs
using Microsoft.Ajax.Utilities;
using RoomReservation.Models;
using RoomReservation.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace RoomReservation.Controllers
{
    public class RoomsController : Controller
    {
        private RoomReservationContext db = new RoomReservationContext();
        List<string> SortTypes = new List<string> { "Beds number", "Beds number descending", "Price", "Price Descending" };
        private int itemsPerPage = 2;

        // GET: Rooms
        public ActionResult Index(/*string search,*/ string sortType = "Beds number", int page = 1)
        {
            var rooms = db.Rooms.Include(r => r.Reservations);

            //if (!search.IsNullOrWhiteSpace())
            //{
            //    rooms = rooms.Where(
            //        x => x.Name.Contains(search) ||
            //        x.Accommodation.Name.Contains(search)
            //    );
            //}

            switch (sortType)
            {
                case "Beds number":
                    rooms = rooms.OrderBy(x => x.BedNumber);
                    break;
                case "Beds number descending":
                    rooms = rooms.OrderByDescending(x => x.BedNumber);
                    break;
                case "Price":
                    rooms = rooms.OrderBy(x => x.Price);
                    break;
                case "Price Descending":
                    rooms = rooms.OrderByDescending(x => x.Price);
                    break;
            }

            var model = new RoomAccommodationsViewModel();
            model.SortTypes = SortTypes;
            model.Rooms = rooms.ToPagedList(page, itemsPerPage);
            return View(model);
        }

        // GET: Rooms/Create
        public ActionResult Create()
        {
            var model = new RoomAccommodationsViewModel();
            model.Accommodations = db.Acommodations.ToList();
            return View(model);
        }

        // POST: Rooms/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomAccommodationsViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Room.AccommodationId = model.selectedAccommodation;
                db.Rooms.Add(model.Room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Rooms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            var model = new RoomAccommodationsViewModel();
            model.Accommodations = db.Acommodations.ToList();
            model.Room = room;
            model.selectedAccommodation = room.AccommodationId;
            return View(model);
        }

        // POST: Rooms/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoomAccommodationsViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Room.AccommodationId = model.selectedAccommodation;
                db.Entry(model.Room).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Filter(RoomAccommodationsViewModel vm, int page = 1)
        {
            var rooms = db.Rooms
                .Include(x => x.Accommodation)
                .Include(x => x.Reservations);

            if (vm.RoomFilter.BedNumberFrom != null)
            {
                rooms = rooms.Where(x => x.BedNumber >= vm.RoomFilter.BedNumberFrom)
                    .OrderBy(x => x.Id);

                //Model.Name = db.Products.Where(p => p.ProductSubcategoryID == id)
                //        .OrderBy(p => p.ProductSubcategoryID) // <---- this
                //        .Skip((page - 1) * pageSize)
                //        .Take(/*pageSize*/ itemsPerPage)
                //        .ToList();
            }

            if (vm.RoomFilter.BedNumberTo != null)
            {
                rooms = rooms.Where(x => x.BedNumber <= vm.RoomFilter.BedNumberTo)
                    .OrderBy(x => x.Id); ;
            }

            if (vm.RoomFilter.PriceFrom != null)
            {
                rooms = rooms.Where(x => x.Price >= vm.RoomFilter.PriceFrom);
            }

            if (vm.RoomFilter.PriceTo != null)
            {
                rooms = rooms.Where(x => x.Price <= vm.RoomFilter.PriceTo);
            }

            if (!vm.RoomFilter.AccommodationName.IsNullOrWhiteSpace())
            {
                rooms = rooms.Where(x => x.Accommodation.Name.Contains(vm.RoomFilter.AccommodationName));
            }

            //if (filter.CreatedFrom != null)
            //{
            //    products = products.Where(p => p.Created >= filter.CreatedFrom);
            //}

            //if (filter.CreatedTo != null)
            //{
            //    products = products.Where(p => p.Created <= filter.CreatedTo);
            //}

            //var model = new RoomAccommodationsViewModel();
            //model.SortTypes = SortTypes;
            vm.Rooms = rooms.ToPagedList(page, itemsPerPage);
            return View(vm);
        }

        // POST: Rooms/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            db.Rooms.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RoomReservation/Views/Rooms/Create.cshtml
@model RoomReservation.ViewModels.RoomAccommodationsViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Room</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Room.RoomNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Room.RoomNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Room.RoomNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Room.BedNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Room.BedNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Room.BedNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Room.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Room.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Room.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Accommodations.FirstOrDefault().Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.selectedAccommodation,
                   new SelectList(Model.Accommodations, "Id", "Name"), new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RoomReservation/Views/Rooms/Edit.cshtml
@model RoomReservation.ViewModels.RoomAccommodationsViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Room</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Room.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Room.RoomNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Room.RoomNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Room.RoomNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Room.BedNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Room.BedNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Room.BedNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Room.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Room.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Room.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Accommodations.FirstOrDefault().Name, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.selectedAccommodation,
                  new SelectList(Model.Accommodations, "Id", "Name"), new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RoomReservation/Views/Rooms/Filter.cshtml
@model RoomReservation.ViewModels.RoomAccommodationsViewModel
@{
    ViewBag.Title = "Filter";
}

<h2>Filter Results</h2>

@{
    Html.RenderPartial("_RoomList");
}
@Html.ActionLink("Go Back", "Index")

RoomReservation/Views/Rooms/Index.cshtml
@using PagedList.Mvc
@model RoomReservation.ViewModels.RoomAccommodationsViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Rooms</h2>

<div class="row">
    <div class="col-sm-4"><button id="filter" class="btn btn-default pull-left">Filter</button></div>
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        @using (Html.BeginForm("Index", "Rooms", FormMethod.Get))
        {
            <input type="submit" value="Sort by" class="btn btn-default" />
            @Html.DropDownListFor(m => m.sortType,
                      new SelectList(Model.SortTypes, Model.SortTypes.FirstOrDefault().ToString()))
        }
    </div>
</div>

<div id="filterForm" class="hidden">
    @using (Html.BeginForm("Filter", "Rooms", FormMethod.Post))
    {
        @Html.LabelFor(m=>m.RoomFilter.BedNumberFrom)
        @Html.EditorFor(m=>m.RoomFilter.BedNumberFrom, new { htmlAttributes = new { @class = "form-control" } })
        @Html.LabelFor(m => m.RoomFilter.BedNumberTo)
        @Html.EditorFor(m => m.RoomFilter.BedNumberTo, new { htmlAttributes = new { @class = "form-control" } })
        @Html.LabelFor(m => m.RoomFilter.PriceFrom)
        @Html.EditorFor(m => m.RoomFilter.PriceFrom, new { htmlAttributes = new { @class = "form-control" } })
        @Html.LabelFor(m => m.RoomFilter.PriceTo)
        @Html.EditorFor(m => m.RoomFilter.PriceTo, new { htmlAttributes = new { @class = "form-control" } })
        @Html.LabelFor(m => m.RoomFilter.AccommodationName)
        @Html.EditorFor(m => m.RoomFilter.AccommodationName, new { htmlAttributes = new { @class = "form-control" } })
        <input type="submit" class="btn btn-info" />
    }
</div>

@{
    Html.RenderPartial("_RoomList");
}
Page @(Model.Rooms.PageCount < Model.Rooms.PageNumber ? 0 : Model.Rooms.PageNumber) of @Model.Rooms.PageCount

@Html.PagedListPager(Model.Rooms, page => Url.Action("Index", new { page }))

@Html.ActionLink("Create new", "Create", null, new { @class = "btn btn-primary" })

RoomReservation/Views/Rooms/_RoomItem.cshtml
@model RoomReservation.Models.Room
<tr>
    <td><b>@ViewBag.num</b></td>
    <td>@Model.RoomNumber</td>
    <td>@Model.BedNumber</td>
    <td>@Model.Price</td>
    <td>@Model.Accommodation.Name</td>
    <td>@Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" })</td>
    <td>
        @using (Html.BeginForm("Delete", "Rooms", new { id = Model.Id }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        }
    </td>
</tr>

RoomReservation/Views/Rooms/_RoomList.cshtml
@model RoomReservation.ViewModels.RoomAccommodationsViewModel

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Room number</th>
            <th>Bed number</th>
            <th>Price</th>
            <th>Accommodation</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{var num = 1;
            ViewBag.num = num;
         }
        @foreach (var item in Model.Rooms)
        {
            Html.RenderPartial("_RoomItem", item);
            num++;
            ViewBag.num = num;
        }
    </tbody>
</table>